# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16dfd230937bb62dfde1fc6c96362946379ff6a33c59613d05d9b31dadb313a2c312ee2012435fc76120d279394b57c26a2f143c2bb2e17ac4f7b28b14bf82f3

test:
  secret_key_base: 8501ff762ab74039593f2153070fca9d669535fc6f7b761f7548a39c2c566a751dedea086233902cf2f388193a9dda2781dbc4218fe50586ce5a61f03768b1fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
